- name: Konfiguracja mojego serwera WWW
  hosts: webservers
  become: true  
  tasks:
    - name: Aktualizacja pakietów
      apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: dist

    - name: Instalacja Nginx
      apt:
        name: nginx
        state: present

    - name: Uruchomienie i włączenie Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Wgraj konfiguracje Reverse Proxy dla Nginxa
      template:
        src: templates/reverse-proxy.conf.j2
        dest: /etc/nginx/sites-available/default
        mode: '0644'
      notify: Restart Nginx 

  handlers:
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted